<?php

namespace AppBundle\Repository;

/**
 * epizy_usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class epizy_usersRepository extends \Doctrine\ORM\EntityRepository
{
}
