<?php

namespace AppBundle\Repository;

/**
 * Epizy_ecoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Epizy_ecoleRepository extends \Doctrine\ORM\EntityRepository
{
}
