<?php

namespace AdminBundle\Repository;

/**
 * epizy_logicielsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class epizy_logicielsRepository extends \Doctrine\ORM\EntityRepository
{
}
