<?php

namespace AdminBundle\Repository;

/**
 * Epizy_demandeur_cvsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Epizy_demandeur_cvsRepository extends \Doctrine\ORM\EntityRepository
{
}
