<?php

namespace AdminBundle\Repository;

/**
 * epizy_secteur_activitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class epizy_secteur_activitesRepository extends \Doctrine\ORM\EntityRepository
{
}
