<?php

namespace AdminBundle\Repository;

/**
 * epizy_emploi_recherchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class epizy_emploi_recherchesRepository extends \Doctrine\ORM\EntityRepository
{
}
