<?php

namespace AdminBundle\Repository;

/**
 * epizy_demandeur_emploisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class epizy_demandeur_emploisRepository extends \Doctrine\ORM\EntityRepository
{
}
