<?php

namespace AdminBundle\Repository;

/**
 * epizy_universitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class epizy_universitesRepository extends \Doctrine\ORM\EntityRepository
{
}
