<?php

namespace AdminBundle\Repository;

/**
 * epizy_poste_occupesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class epizy_poste_occupesRepository extends \Doctrine\ORM\EntityRepository
{
}
