<?php

namespace AdminBundle\Repository;

/**
 * epizy_villesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class epizy_villesRepository extends \Doctrine\ORM\EntityRepository
{
}
