<?php

namespace AdminBundle\Repository;

/**
 * epizy_diplomesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class epizy_diplomesRepository extends \Doctrine\ORM\EntityRepository
{
}
